### ISSUE TITLE
arrow property in Link

### ISSUE THREAD

**Issue by veeramarni** [xuyuanxiang/umi-react-native#13]
Can you show from where this `Link` is pulled from? Umi document doesnt' say it has `arrow` property in the `Link`.

```

<Link to="/home" component={Item} arrow="horizontal">

```

**Comment by xuyuanxiang** [comment]
The arrow property is passed to the `Item` referenced by the component property.

Umi uses router-router as it's built-in routing solution. 

You can view the implementation of the Link component’s render method:

[react-router/packages/react-router-native/Link.js Line 27](https://github.com/ReactTraining/react-router/blob/42933fe141819e4662113ab2c320bf86be3490fb/packages/react-router-native/Link.js#L27)

```
  render() {
    const { component: Component, to, replace, ...rest } = this.props;

    return (
      <HistoryContext.Consumer>
        {history => (
          <Component
            {...rest}
            onPress={event => this.handlePress(event, history)}
          />
        )}
      </HistoryContext.Consumer>
    );
  }
```
**It receives all rest parameters from the properties of the `Link` and passes them to the `Component`.**
